#coding:utf-8   #encodage du logiciel, utf 8 étant pour les langues latines
from tkinter import *   #importation de la bibliothèque tkinter

window=Tk() #création de la fenêtre d'authentification

window.title("Stephi Place Real Estate Software")   #caractéristiques de la fenêtre : nom, taille, couleur de fond, icone.
window.maxsize(600, 200)
window.minsize(600, 200)
window.configure(bg='#303030')
window.iconbitmap("hc.ico")

def action():   #fonction qui lorsque l'on appui sur le bouton lié à la commande "action_a" lance les actions suivantes
    import mysql.connector as MC    #importation de mysqlconnector permettant d'établir une connexion entre la base de données MYSQL et Python 3
    try:
        conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')    #on se connecte à la base de données
        cursor = conn.cursor()  #création d'un curseur de connexion
        value_user = (value.get())  #récupération de la chaîne de caractère associée à l'input
        cursor.execute("SELECT identifiant_administrateur FROM administrateur WHERE identifiant_administrateur=%s", (value_user,))  #on intégre la variable précédente à la requête MYSQL, qui ira chercher dans la base de donner cette dite variable
        admin_list = cursor.fetchall()  #affichage de tous les élements, il existe aussi fecthone pour afficher un élément et fetchmany
        for admin in admin_list:    #création d'une liste regroupant les résultats de la requête
            admin = (admin[0])  #on ne récupère qu'un seul élément, à savoir l'identifiant, le premier élément correspond donc à la valeur 0 dans ma liste
            if value_user == admin: #ici on effectue la vérification de l'identifiant, si i lexiste dans la base de données, alors on peut passer aux actions suivantes
                window.destroy()    #dans ce cas on détruit la fenêtre précédente

                def action_connexion():
                    value_nom = (entry_nom_administrateur.get())
                    for admin in admin_list:
                        admin = (admin[10])
                        if value_nom == admin:
                            generalwindow.destroy()

                            def action_connexion_2():
                                value_nom_2 = (entry_nom_administrateur_2.get())
                                for admin in admin_list:
                                    admin = (admin[11])
                                    if value_nom_2 == admin:
                                        generalwindow_2.destroy()

                                        import mysql.connector as MC

                                        window_annonces_1=Tk()
                                        window_annonces_1.title("Stephi Place Real Estate Software")
                                        window_annonces_1.maxsize(1200, 600)
                                        window_annonces_1.minsize(1200, 600)
                                        window_annonces_1.configure(bg='#303030')
                                        window_annonces_1.iconbitmap("hc.ico")

                                        def create_1():
                                            window_annonces_2=Tk()
                                            window_annonces_2.title("Stephi Place Real Estate Software")
                                            window_annonces_2.maxsize(1200, 600)
                                            window_annonces_2.minsize(1200, 600)
                                            window_annonces_2.configure(bg='#303030')
                                            window_annonces_2.iconbitmap("hc.ico")

                                            def button_quitter():
                                                window_annonces_2.destroy()

                                            def valider_creation2():
                                                import mysql.connector as MC

                                                try:
                                                    conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                    cursor = conn.cursor()

                                                    var_1_annonce2 = (value_annonce2_0_entry.get())
                                                    var_2_annonce2 = (value_annonce2_1_entry.get())
                                                    var_3_annonce2 = (value_annonce2_2_entry.get())
                                                    var_4_annonce2 = (value_annonce2_3_entry.get("1.0",END))    #pour récupérer les informations d'un "text tkinter", il faut ajouter ces deux attributs
                                                    var_5_annonce2 = (value_annonce2_4_entry.get())
                                                    var_6_annonce2 = (value_annonce2_5_entry.get())
                                                    var_7_annonce2 = (value_annonce2_6_entry.get())
                                                    var_8_annonce2 = (value_annonce2_7_entry.get())
                                                    var_9_annonce2 = (value_annonce2_8_entry.get())
                                                    var_10_annonce2 = (value_annonce2_9_entry.get())
                                                    var_11_annonce2 = (value_annonce2_10_entry.get())
                                                    var_12_annonce2 = (value_annonce2_11_entry.get())
                                                    var_13_annonce2 = (value_annonce2_12_entry.get())
                                                    var_14_annonce2 = (value_annonce2_13_entry.get())
                                                    var_15_annonce2 = (value_annonce2_14_entry.get())
                                                    var_16_annonce2 = (value_annonce2_15_entry.get())
                                                    var_17_annonce2 = (value_annonce2_16_entry.get())
                                                    var_18_annonce2 = (value_annonce2_17_entry.get())


                                                    cursor.execute("INSERT INTO annonces (identifiant_annonce, titre_annonce, nombredepieces_annonce, description_annonce, superficie_annonce, prix_annonce, ville_annonce, codepostale_annonce, type_annonce, fraisagence_annonce, visavis_annonce, lieu_annonce, piscine_annonce, jardin_annonce, parkingprive_annonce, superficiejardin_annonce, agent_annonce, statut_annonces) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (var_1_annonce2, var_2_annonce2, var_3_annonce2, var_4_annonce2, var_5_annonce2, var_6_annonce2, var_7_annonce2, var_8_annonce2, var_9_annonce2, var_10_annonce2, var_11_annonce2, var_12_annonce2, var_13_annonce2, var_14_annonce2, var_15_annonce2, var_16_annonce2, var_17_annonce2, var_18_annonce2))
                                                    conn.commit()   #le ".commit" est très important, puisque sans lui, si l'on modifie des données de la base, ces modifications ne seront pas sauvegardées

                                                except MC.Error as err: #si la connexion a échoué, on affiche un message d'erreur
                                                    print(err)
                                                finally:    #si la connexion est ok et que les requêtes ont été effectuées, on coupe la connexion
                                                    if(conn.is_connected()):
                                                        cursor.close()
                                                        conn.close()

                                            button_valider_creation2 = Button(window_annonces_2, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = valider_creation2, text = "Valider")   #création d'un bouton avec tkinter, on défini son type, sur quelle fenêtre il doit apparaître, sa largeur, sa couleur de fond, sa police et sa taille, à quelle commande i lest assigné et enfin le message écrit sur le bouton
                                            button_valider_creation2.place(x = 200 , y = 50)    #on le positionne grâce à des coordonnées, comme dans un plan orthonormé, x étant l'axe horizontal et y vertical
                                            button_quitter = Button(window_annonces_2, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = button_quitter, text = "Quitter")
                                            button_quitter.place(x = 800 , y = 50)
                                            annonce3_label_1 = Label(window_annonces_2, width = 20, text = " Identifiant -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_1.place(x = 40, y = 129)
                                            annonce3_label_2 = Label(window_annonces_2, width = 20, text = " Titre -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_2.place(x = 40, y = 149)
                                            annonce3_label_3 = Label(window_annonces_2, width = 20, text = " Nombre de pièces -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_3.place(x = 40, y = 169)
                                            annonce3_label_5 = Label(window_annonces_2, width = 20, text = " Superficie -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_5.place(x = 40, y = 309)
                                            annonce3_label_6 = Label(window_annonces_2, width = 20, text = " Prix -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_6.place(x = 40, y = 329)
                                            annonce3_label_7 = Label(window_annonces_2, width = 20, text = " Ville -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_7.place(x = 40, y = 349)
                                            annonce3_label_8 = Label(window_annonces_2, width = 20, text = " Code postal -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_8.place(x = 40, y = 369)
                                            annonce3_label_9 = Label(window_annonces_2, width = 20, text = " Type -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_9.place(x = 40, y = 389)
                                            annonce3_label_10 = Label(window_annonces_2, width = 20, text = " Frais agence -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_10.place(x = 40, y = 409)
                                            annonce3_label_11 = Label(window_annonces_2, width = 20, text = " Vis à vis -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_11.place(x = 40, y = 429)
                                            annonce3_label_12 = Label(window_annonces_2, width = 20, text = " Lieu -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_12.place(x = 40, y = 449)
                                            annonce3_label_13 = Label(window_annonces_2, width = 20, text = " Piscine -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_13.place(x = 40, y = 469)
                                            annonce3_label_14 = Label(window_annonces_2, width = 20, text = " Jardin -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_14.place(x = 40, y = 489)
                                            annonce3_label_15 = Label(window_annonces_2, width = 20, text = " Parking privé -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_15.place(x = 40, y = 509)
                                            annonce3_label_16 = Label(window_annonces_2, width = 20, text = " Superficie jardin -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_16.place(x = 40, y = 529)
                                            annonce3_label_17 = Label(window_annonces_2, width = 20, text = " Agent responsable -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_17.place(x = 40, y = 549)
                                            annonce3_label_18 = Label(window_annonces_2, width = 20, text = " Disponibilité -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce3_label_18.place(x = 40, y = 569)
                                            value_annonce2_0_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_0_entry.place(x = 200, y = 130)
                                            value_annonce2_1_entry = Entry(window_annonces_2, width = 95, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_1_entry.place(x = 200, y = 150)
                                            value_annonce2_2_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_2_entry.place(x = 200, y = 170)
                                            value_annonce2_3_entry = Text(window_annonces_2, width = 130, height = 7, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_3_entry.place(x = 200, y = 195)
                                            value_annonce2_4_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_4_entry.place(x = 200, y = 310)
                                            value_annonce2_5_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_5_entry.place(x = 200, y = 330)
                                            value_annonce2_6_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_6_entry.place(x = 200, y = 350)
                                            value_annonce2_7_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_7_entry.place(x = 200, y = 370)
                                            value_annonce2_8_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_8_entry.place(x = 200, y = 390)
                                            value_annonce2_9_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_9_entry.place(x = 200, y = 410)
                                            value_annonce2_10_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_10_entry.place(x = 200, y = 430)
                                            value_annonce2_11_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_11_entry.place(x = 200, y = 450)
                                            value_annonce2_12_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_12_entry.place(x = 200, y = 470)
                                            value_annonce2_13_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_13_entry.place(x = 200, y = 490)
                                            value_annonce2_14_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_14_entry.place(x = 200, y = 510)
                                            value_annonce2_15_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_15_entry.place(x = 200, y = 530)
                                            value_annonce2_16_entry = Entry(window_annonces_2, width = 45, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_16_entry.place(x = 200, y = 550)
                                            value_annonce2_17_entry = Entry(window_annonces_2, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce2_17_entry.place(x = 200, y = 570)
                                            window_annonces_2.mainloop()

                                        def update_1():
                                            window_annonces_4=Tk()
                                            window_annonces_4.title("Stephi Place Real Estate Software")
                                            window_annonces_4.maxsize(1200, 600)
                                            window_annonces_4.minsize(1200, 600)
                                            window_annonces_4.configure(bg='#303030')
                                            window_annonces_4.iconbitmap("hc.ico")

                                            def action_research():
                                                try:
                                                    conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                    cursor = conn.cursor()
                                                    value_annonce_4 = (value_annonce4_entry.get())
                                                    cursor.execute("SELECT * FROM annonces WHERE identifiant_annonce=%s", (value_annonce_4,))
                                                    annonce_list_1 = cursor.fetchall()
                                                    for annonce in annonce_list_1:  #cette liste nous permet de récupérer les toutes les données de la table "annonces"
                                                        annonce_0 = (annonce[1])
                                                        value_annonce4_0_entry.delete(0, 500)   #avant d'afficher le résultat de la requête on supprime tout ce qui pourrait déjà si trouver, en effet si l'utilisateur effectue deux requêtes consécutives, les deux requêtes seront affichées dans les inputs qiu leurs sont associées
                                                        value_annonce4_0_entry.insert(0, annonce_0) #les attributs font que la donnée de la variable annonce_0 sera affichée dès le début de l'input(0)
                                                        annonce_1 = (annonce[2])
                                                        value_annonce4_1_entry.delete(0, 500)
                                                        value_annonce4_1_entry.insert(0, annonce_1)
                                                        annonce_2 = (annonce[3])
                                                        value_annonce4_2_entry.delete(0, 500)
                                                        value_annonce4_2_entry.insert(0, annonce_2)
                                                        annonce_3 = (annonce[4])
                                                        value_annonce4_3_entry.delete(1.0, END)
                                                        value_annonce4_3_entry.insert(END, annonce_3)
                                                        annonce_4 = (annonce[5])
                                                        value_annonce4_4_entry.delete(0, 500)
                                                        value_annonce4_4_entry.insert(0, annonce_4)
                                                        annonce_5 = (annonce[6])
                                                        value_annonce4_5_entry.delete(0, 500)
                                                        value_annonce4_5_entry.insert(0, annonce_5)
                                                        annonce_6 = (annonce[7])
                                                        value_annonce4_6_entry.delete(0, 500)
                                                        value_annonce4_6_entry.insert(0, annonce_6)
                                                        annonce_7 = (annonce[8])
                                                        value_annonce4_7_entry.delete(0, 500)
                                                        value_annonce4_7_entry.insert(0, annonce_7)
                                                        annonce_8 = (annonce[9])
                                                        value_annonce4_8_entry.delete(0, 500)
                                                        value_annonce4_8_entry.insert(0, annonce_8)
                                                        annonce_9 = (annonce[10])
                                                        value_annonce4_9_entry.delete(0, 500)
                                                        value_annonce4_9_entry.insert(0, annonce_9)
                                                        annonce_10 = (annonce[11])
                                                        value_annonce4_10_entry.delete(0, 500)
                                                        value_annonce4_10_entry.insert(0, annonce_10)
                                                        annonce_11 = (annonce[12])
                                                        value_annonce4_11_entry.delete(0, 500)
                                                        value_annonce4_11_entry.insert(0, annonce_11)
                                                        annonce_12 = (annonce[13])
                                                        value_annonce4_12_entry.delete(0, 500)
                                                        value_annonce4_12_entry.insert(0, annonce_12)
                                                        annonce_13 = (annonce[14])
                                                        value_annonce4_13_entry.delete(0, 500)
                                                        value_annonce4_13_entry.insert(0, annonce_13)
                                                        annonce_14 = (annonce[15])
                                                        value_annonce4_14_entry.delete(0, 500)
                                                        value_annonce4_14_entry.insert(0, annonce_14)
                                                        annonce_15 = (annonce[16])
                                                        value_annonce4_15_entry.delete(0, 500)
                                                        value_annonce4_15_entry.insert(0, annonce_15)
                                                        annonce_16 = (annonce[17])
                                                        value_annonce4_16_entry.delete(0, 500)
                                                        value_annonce4_16_entry.insert(0, annonce_16)
                                                        annonce_17 = (annonce[18])
                                                        value_annonce4_17_entry.delete(0, 500)
                                                        value_annonce4_17_entry.insert(0, annonce_17)

                                                except MC.Error as err:
                                                    print(err)
                                                finally:
                                                    if(conn.is_connected()):
                                                        cursor.close()
                                                        conn.close()

                                            def button_quitter4():
                                                window_annonces_4.destroy()

                                            def valider_creation4():
                                                import mysql.connector as MC

                                                try:
                                                    conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                    cursor = conn.cursor()

                                                    value_annonce_4 = (value_annonce4_entry.get())
                                                    var_1_annonce4 = (value_annonce4_0_entry.get())
                                                    var_2_annonce4 = (value_annonce4_1_entry.get())
                                                    var_3_annonce4 = (value_annonce4_2_entry.get())
                                                    var_4_annonce4 = (value_annonce4_3_entry.get("1.0",END))
                                                    var_5_annonce4 = (value_annonce4_4_entry.get())
                                                    var_6_annonce4 = (value_annonce4_5_entry.get())
                                                    var_7_annonce4 = (value_annonce4_6_entry.get())
                                                    var_8_annonce4 = (value_annonce4_7_entry.get())
                                                    var_9_annonce4 = (value_annonce4_8_entry.get())
                                                    var_10_annonce4 = (value_annonce4_9_entry.get())
                                                    var_11_annonce4 = (value_annonce4_10_entry.get())
                                                    var_12_annonce4 = (value_annonce4_11_entry.get())
                                                    var_13_annonce4 = (value_annonce4_12_entry.get())
                                                    var_14_annonce4 = (value_annonce4_13_entry.get())
                                                    var_15_annonce4 = (value_annonce4_14_entry.get())
                                                    var_16_annonce4 = (value_annonce4_15_entry.get())
                                                    var_17_annonce4 = (value_annonce4_16_entry.get())
                                                    var_18_annonce4 = (value_annonce4_17_entry.get())

                                                    cursor.execute("""
                                                        UPDATE annonces
                                                        SET identifiant_annonce=%s, titre_annonce=%s, nombredepieces_annonce=%s, description_annonce=%s, superficie_annonce=%s, prix_annonce=%s, ville_annonce=%s, codepostale_annonce=%s, type_annonce=%s, fraisagence_annonce=%s, visavis_annonce=%s, lieu_annonce=%s, piscine_annonce=%s, jardin_annonce=%s, parkingprive_annonce=%s, superficiejardin_annonce=%s, agent_annonce=%s, statut_annonces=%s
                                                        WHERE identifiant_annonce=%s
                                                        """,(var_1_annonce4, var_2_annonce4, var_3_annonce4, var_4_annonce4, var_5_annonce4, var_6_annonce4, var_7_annonce4, var_8_annonce4, var_9_annonce4, var_10_annonce4, var_11_annonce4, var_12_annonce4, var_13_annonce4, var_14_annonce4, var_15_annonce4, var_16_annonce4, var_17_annonce4, var_18_annonce4, value_annonce_4))
                                                    conn.commit()

                                                except MC.Error as err:
                                                    print(err)
                                                finally:
                                                    if(conn.is_connected()):
                                                        cursor.close()
                                                        conn.close()

                                            value_annonce4_entry = Entry(window_annonces_4, width = 40, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_entry.place(x = 50, y = 53)
                                            value_annonce_1_input = Button(window_annonces_4, width = 25,bg = "#D5D5D5", font = ("Helvetica", 11), text = "Rechercher", command = action_research)
                                            value_annonce_1_input.place(x = 350, y = 50)
                                            button4_valider_creation2 = Button(window_annonces_4, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = valider_creation4, text = "Valider")
                                            button4_valider_creation2.place(x = 700 , y = 50)
                                            button4_quitter = Button(window_annonces_4, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = button_quitter4, text = "Quitter")
                                            button4_quitter.place(x = 1000 , y = 50)
                                            annonce4_label_1 = Label(window_annonces_4, width = 20, text = " Identifiant -> ", bg = "#D5D5D5", font = ("Helvetica", 8)) #création d'un label tkinter permettant d'afficher du texte
                                            annonce4_label_1.place(x = 40, y = 129)
                                            annonce4_label_2 = Label(window_annonces_4, width = 20, text = " Titre -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_2.place(x = 40, y = 149)
                                            annonce4_label_3 = Label(window_annonces_4, width = 20, text = " Nombre de pièces -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_3.place(x = 40, y = 169)
                                            annonce4_label_5 = Label(window_annonces_4, width = 20, text = " Superficie -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_5.place(x = 40, y = 309)
                                            annonce4_label_6 = Label(window_annonces_4, width = 20, text = " Prix -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_6.place(x = 40, y = 329)
                                            annonce4_label_7 = Label(window_annonces_4, width = 20, text = " Ville -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_7.place(x = 40, y = 349)
                                            annonce4_label_8 = Label(window_annonces_4, width = 20, text = " Code postal -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_8.place(x = 40, y = 369)
                                            annonce4_label_9 = Label(window_annonces_4, width = 20, text = " Type -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_9.place(x = 40, y = 389)
                                            annonce4_label_10 = Label(window_annonces_4, width = 20, text = " Frais agence -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_10.place(x = 40, y = 409)
                                            annonce4_label_11 = Label(window_annonces_4, width = 20, text = " Vis à vis -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_11.place(x = 40, y = 429)
                                            annonce4_label_12 = Label(window_annonces_4, width = 20, text = " Lieu -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_12.place(x = 40, y = 449)
                                            annonce4_label_13 = Label(window_annonces_4, width = 20, text = " Piscine -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_13.place(x = 40, y = 469)
                                            annonce4_label_14 = Label(window_annonces_4, width = 20, text = " Jardin -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_14.place(x = 40, y = 489)
                                            annonce4_label_15 = Label(window_annonces_4, width = 20, text = " Parking privé -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_15.place(x = 40, y = 509)
                                            annonce4_label_16 = Label(window_annonces_4, width = 20, text = " Superficie jardin -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_16.place(x = 40, y = 529)
                                            annonce4_label_17 = Label(window_annonces_4, width = 20, text = " Agent responsable -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_17.place(x = 40, y = 549)
                                            annonce4_label_18 = Label(window_annonces_4, width = 20, text = " Disponibilité -> ", bg = "#D5D5D5", font = ("Helvetica", 8))
                                            annonce4_label_18.place(x = 40, y = 569)
                                            value_annonce4_0_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))  #création d'un entry tkinter permettant à l'utilisateur d'intrer une valeur mais aussi au logiciel d'en afficher une
                                            value_annonce4_0_entry.place(x = 200, y = 130)
                                            value_annonce4_1_entry = Entry(window_annonces_4, width = 95, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_1_entry.place(x = 200, y = 150)
                                            value_annonce4_2_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_2_entry.place(x = 200, y = 170)
                                            value_annonce4_3_entry = Text(window_annonces_4, width = 130, height = 7, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_3_entry.place(x = 200, y = 195)
                                            value_annonce4_4_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_4_entry.place(x = 200, y = 310)
                                            value_annonce4_5_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_5_entry.place(x = 200, y = 330)
                                            value_annonce4_6_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_6_entry.place(x = 200, y = 350)
                                            value_annonce4_7_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_7_entry.place(x = 200, y = 370)
                                            value_annonce4_8_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_8_entry.place(x = 200, y = 390)
                                            value_annonce4_9_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_9_entry.place(x = 200, y = 410)
                                            value_annonce4_10_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_10_entry.place(x = 200, y = 430)
                                            value_annonce4_11_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_11_entry.place(x = 200, y = 450)
                                            value_annonce4_12_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_12_entry.place(x = 200, y = 470)
                                            value_annonce4_13_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_13_entry.place(x = 200, y = 490)
                                            value_annonce4_14_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_14_entry.place(x = 200, y = 510)
                                            value_annonce4_15_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_15_entry.place(x = 200, y = 530)
                                            value_annonce4_16_entry = Entry(window_annonces_4, width = 45, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_16_entry.place(x = 200, y = 550)
                                            value_annonce4_17_entry = Entry(window_annonces_4, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                            value_annonce4_17_entry.place(x = 200, y = 570)
                                            window_annonces_4.mainloop()

                                        def delete_1():
                                            import mysql.connector as MC

                                            try:
                                                conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                cursor = conn.cursor()
                                                value_annonce_1 = (value_annonce_1_entry.get())
                                                cursor.execute("DELETE FROM annonces WHERE identifiant_annonce=%s", (value_annonce_1,))
                                                conn.commit()

                                            except MC.Error as err:
                                                print(err)
                                            finally:
                                                if(conn.is_connected()):
                                                    cursor.close()
                                                    conn.close()

                                        def clear_1():
                                                try:
                                                    conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                    cursor = conn.cursor()
                                                    value_annonce_1 = (value_annonce_1_entry.get())
                                                    cursor.execute("SELECT * FROM annonces WHERE identifiant_annonce=%s", (value_annonce_1,))
                                                    annonce_list_1 = cursor.fetchall()
                                                    value_annonce_1_entry.delete(0, 500)
                                                    for annonce in annonce_list_1:
                                                        annonce_0 = (annonce[0])
                                                        value_annonce_2_entry.delete(0, 500)
                                                        annonce_1 = (annonce[1])
                                                        value_annonce_3_entry.delete(0, 500)
                                                        annonce_2 = (annonce[2])
                                                        value_annonce_4_entry.delete(0, 500)
                                                        annonce_3 = (annonce[3])
                                                        value_annonce_5_entry.delete(0, 500)
                                                        annonce_4 = (annonce[4])
                                                        value_annonce_6_entry.delete(1.0, END)
                                                        annonce_5 = (annonce[5])
                                                        value_annonce_7_entry.delete(0, 500)
                                                        annonce_6 = (annonce[6])
                                                        value_annonce_8_entry.delete(0, 500)
                                                        annonce_7 = (annonce[7])
                                                        value_annonce_9_entry.delete(0, 500)
                                                        annonce_8 = (annonce[8])
                                                        value_annonce_10_entry.delete(0, 500)
                                                        annonce_9 = (annonce[9])
                                                        value_annonce_11_entry.delete(0, 500)
                                                        annonce_10 = (annonce[10])
                                                        value_annonce_12_entry.delete(0, 500)
                                                        annonce_11 = (annonce[11])
                                                        value_annonce_13_entry.delete(0, 500)
                                                        annonce_12 = (annonce[12])
                                                        value_annonce_14_entry.delete(0, 500)
                                                        annonce_13 = (annonce[13])
                                                        value_annonce_15_entry.delete(0, 500)
                                                        annonce_14 = (annonce[14])
                                                        value_annonce_16_entry.delete(0, 500)
                                                        annonce_15 = (annonce[15])
                                                        value_annonce_17_entry.delete(0, 500)
                                                        annonce_16 = (annonce[16])
                                                        value_annonce_18_entry.delete(0, 500)
                                                        annonce_17 = (annonce[17])
                                                        value_annonce_19_entry.delete(0, 500)
                                                        annonce_18 = (annonce[18])
                                                        value_annonce_20_entry.delete(0, 500)

                                                except MC.Error as err:
                                                    print(err)
                                                finally:
                                                    if(conn.is_connected()):
                                                        cursor.close()
                                                        conn.close()

                                        def action_a():
                                            try:
                                                conn = MC.connect(host = 'localhost', database = 'stephi_place_bd', user = 'root', password = '')
                                                cursor = conn.cursor()
                                                value_annonce_1 = (value_annonce_1_entry.get())
                                                cursor.execute("SELECT * FROM annonces WHERE identifiant_annonce=%s", (value_annonce_1,))
                                                annonce_list_1 = cursor.fetchall()
                                                for annonce in annonce_list_1:
                                                    annonce_0 = (annonce[0])
                                                    value_annonce_2_entry.delete(0, 500)
                                                    value_annonce_2_entry.insert(0, " id : ")
                                                    value_annonce_2_entry.insert(8, annonce_0)
                                                    annonce_1 = (annonce[1])
                                                    value_annonce_3_entry.delete(0, 500)
                                                    value_annonce_3_entry.insert(0, " identifiant : ")
                                                    value_annonce_3_entry.insert(15, annonce_1)
                                                    annonce_2 = (annonce[2])
                                                    value_annonce_4_entry.delete(0, 500)
                                                    value_annonce_4_entry.insert(0, " Titre : ")
                                                    value_annonce_4_entry.insert(9, annonce_2)
                                                    annonce_3 = (annonce[3])
                                                    value_annonce_5_entry.delete(0, 500)
                                                    value_annonce_5_entry.insert(0, " Nombre de pièces : ")
                                                    value_annonce_5_entry.insert(20, annonce_3)
                                                    annonce_4 = (annonce[4])
                                                    value_annonce_6_entry.delete(1.0, END)
                                                    value_annonce_6_entry.insert(END, annonce_4)
                                                    annonce_5 = (annonce[5])
                                                    value_annonce_7_entry.delete(0, 500)
                                                    value_annonce_7_entry.insert(0, " Superficie : ")
                                                    value_annonce_7_entry.insert(14, annonce_5)
                                                    value_annonce_7_entry.insert(100, " m2 ")
                                                    annonce_6 = (annonce[6])
                                                    value_annonce_8_entry.delete(0, 500)
                                                    value_annonce_8_entry.insert(0, " Prix : ")
                                                    value_annonce_8_entry.insert(8, annonce_6)
                                                    value_annonce_8_entry.insert(80, " € ")
                                                    annonce_7 = (annonce[7])
                                                    value_annonce_9_entry.delete(0, 500)
                                                    value_annonce_9_entry.insert(0, " Ville : ")
                                                    value_annonce_9_entry.insert(9, annonce_7)
                                                    annonce_8 = (annonce[8])
                                                    value_annonce_10_entry.delete(0, 500)
                                                    value_annonce_10_entry.insert(0, " Code postal : ")
                                                    value_annonce_10_entry.insert(15, annonce_8)
                                                    annonce_9 = (annonce[9])
                                                    value_annonce_11_entry.delete(0, 500)
                                                    value_annonce_11_entry.insert(0, " Type : ")
                                                    value_annonce_11_entry.insert(8, annonce_9)
                                                    annonce_10 = (annonce[10])
                                                    value_annonce_12_entry.delete(0, 500)
                                                    value_annonce_12_entry.insert(0, " Frais d'agence : ")  #pour que l'utilisateur sâche à quoi correspond la valeur d'un input sans ajouter de label, nous pouvons directement écrire dans l'input
                                                    value_annonce_12_entry.insert(18, annonce_10)   #l'affiche des données se font après l'affichage du message précédent, d'où l'attribut qui est égal à 18
                                                    value_annonce_12_entry.insert(100, " € ")   #idem pour € qui s'affiche après le message et la variable
                                                    annonce_11 = (annonce[11])
                                                    value_annonce_13_entry.delete(0, 500)
                                                    value_annonce_13_entry.insert(0, " Vis à vis : ")
                                                    value_annonce_13_entry.insert(13, annonce_11)
                                                    annonce_12 = (annonce[12])
                                                    value_annonce_14_entry.delete(0, 500)
                                                    value_annonce_14_entry.insert(0, " lieu : ")
                                                    value_annonce_14_entry.insert(8, annonce_12)
                                                    annonce_13 = (annonce[13])
                                                    value_annonce_15_entry.delete(0, 500)
                                                    value_annonce_15_entry.insert(0, " Piscine : ")
                                                    value_annonce_15_entry.insert(11, annonce_13)
                                                    annonce_14 = (annonce[14])
                                                    value_annonce_16_entry.delete(0, 500)
                                                    value_annonce_16_entry.insert(0, " Jardin : ")
                                                    value_annonce_16_entry.insert(10, annonce_14)
                                                    annonce_15 = (annonce[15])
                                                    value_annonce_17_entry.delete(0, 500)
                                                    value_annonce_17_entry.insert(0, " Parking privé : ")
                                                    value_annonce_17_entry.insert(17, annonce_15)
                                                    annonce_16 = (annonce[16])
                                                    value_annonce_18_entry.delete(0, 500)
                                                    value_annonce_18_entry.insert(0, " Superficie du jardin : ")
                                                    value_annonce_18_entry.insert(24, annonce_16)
                                                    value_annonce_18_entry.insert(100, " m2 ")
                                                    annonce_17 = (annonce[17])
                                                    value_annonce_19_entry.delete(0, 500)
                                                    value_annonce_19_entry.insert(0, " Responsable de la vente : ")
                                                    value_annonce_19_entry.insert(27, annonce_17)
                                                    annonce_18 = (annonce[18])
                                                    value_annonce_20_entry.delete(0, 500)
                                                    value_annonce_20_entry.insert(0, " Disponibilité : ")
                                                    value_annonce_20_entry.insert(17, annonce_18)

                                            except MC.Error as err:
                                                print(err)
                                            finally:
                                                if(conn.is_connected()):
                                                    cursor.close()
                                                    conn.close()

                                        value_annonce_1_entry = Entry(window_annonces_1, width = 40, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_1_entry.place(x = 200, y = 40)
                                        value_annonce_1_input = Button(window_annonces_1, width = 25, height = 1,bg = "#D5D5D5", font = ("Helvetica", 9), text = "Rechercher", command = action_a)
                                        value_annonce_1_input.place(x = 500, y = 38)
                                        button_create_1 = Button(window_annonces_1, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = create_1, text = "Create")
                                        button_create_1.place(x = 10 , y = 100)
                                        button_delete_1 = Button(window_annonces_1, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = delete_1,text = "Delete")
                                        button_delete_1.place(x = 10 , y = 200)
                                        button_update_1 = Button(window_annonces_1, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = update_1,text = "Update")
                                        button_update_1.place(x = 10 , y = 300)
                                        button_clear_1 = Button(window_annonces_1, width = 15, bg = "#D5D5D5", font = ("Helvetica", 11), command = clear_1,text = "Clear")
                                        button_clear_1.place(x = 10 , y = 400)
                                        value_annonce_2_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_2_entry.place(x = 200, y = 110)
                                        value_annonce_3_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_3_entry.place(x = 200, y = 130)
                                        value_annonce_4_entry = Entry(window_annonces_1, width = 95, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_4_entry.place(x = 200, y = 150)
                                        value_annonce_5_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_5_entry.place(x = 200, y = 170)
                                        value_annonce_6_entry = Text(window_annonces_1, width = 130, height = 7, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_6_entry.place(x = 200, y = 195)
                                        value_annonce_7_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_7_entry.place(x = 200, y = 310)
                                        value_annonce_8_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_8_entry.place(x = 200, y = 330)
                                        value_annonce_9_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_9_entry.place(x = 200, y = 350)
                                        value_annonce_10_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_10_entry.place(x = 200, y = 370)
                                        value_annonce_11_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_11_entry.place(x = 200, y = 390)
                                        value_annonce_12_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_12_entry.place(x = 200, y = 410)
                                        value_annonce_13_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_13_entry.place(x = 200, y = 430)
                                        value_annonce_14_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_14_entry.place(x = 200, y = 450)
                                        value_annonce_15_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_15_entry.place(x = 200, y = 470)
                                        value_annonce_16_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_16_entry.place(x = 200, y = 490)
                                        value_annonce_17_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_17_entry.place(x = 200, y = 510)
                                        value_annonce_18_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_18_entry.place(x = 200, y = 530)
                                        value_annonce_19_entry = Entry(window_annonces_1, width = 45, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_19_entry.place(x = 200, y = 550)
                                        value_annonce_20_entry = Entry(window_annonces_1, width = 25, bg = "#d1a0ad", font = ("Helvetica", 9))
                                        value_annonce_20_entry.place(x = 200, y = 570)
                                        window_annonces_1.mainloop()

                            generalwindow_2=Tk()
                            generalwindow_2.title("Stephi Place Real Estate Software")
                            generalwindow_2.maxsize(600, 200)
                            generalwindow_2.minsize(600, 200)
                            generalwindow_2.configure(bg='#303030')
                            generalwindow_2.iconbitmap("hc.ico")
                            label_title_2 = Label(generalwindow_2, width = 64, bg = "#d1a0ad", font = ("Helvetica", 11), text = "Stephi Place Real Estate Software, Authentification")
                            label_title_2.place(x = 10 , y = 30)
                            label_nom_administrateur_2 = Label(generalwindow_2, width = 20, height = 2, bg = "#d1a0ad", font = ("Helvetica", 10), text = " Votre Code -> ")
                            label_nom_administrateur_2.place(x = 105, y = 70)
                            entry_nom_administrateur_2 = Entry(generalwindow_2, width = 35, bg = "#d1a0ad", show='*', font = ("Helvetica", 10))
                            entry_nom_administrateur_2.place(x = 305, y = 78)
                            button_validation_administrateur_2 = Button(generalwindow_2, width = 20, height = 2,bg = "#D5D5D5", font = ("Helvetica", 8), text = "Valider", command = action_connexion_2)
                            button_validation_administrateur_2.place(x = 230, y = 120)
                            generalwindow_2.mainloop()

                generalwindow=Tk()
                generalwindow.title("Stephi Place Real Estate Software")
                generalwindow.maxsize(600, 200)
                generalwindow.minsize(600, 200)
                generalwindow.configure(bg='#303030')
                generalwindow.iconbitmap("hc.ico")

                cursor.execute("SELECT * FROM administrateur WHERE identifiant_administrateur=%s", (value_user,))
                admin_list = cursor.fetchall()

                label_title = Label(generalwindow, width = 64, bg = "#d1a0ad", font = ("Helvetica", 11), text = "Stephi Place Real Estate Software, Authentification")
                label_title.place(x = 10 , y = 20)
                label_nom_administrateur = Label(generalwindow, width = 20, height = 2, bg = "#d1a0ad", font = ("Helvetica", 10), text = " Votre Email -> ")
                label_nom_administrateur.place(x = 105, y = 60)
                entry_nom_administrateur = Entry(generalwindow, width = 35, bg = "#d1a0ad", font = ("Helvetica", 10))
                entry_nom_administrateur.place(x = 305, y = 68)
                button_validation_administrateur = Button(generalwindow, width = 20, height = 2,bg = "#D5D5D5", font = ("Helvetica", 8), text = "Valider", command = action_connexion)
                button_validation_administrateur.place(x = 230, y = 120)
                generalwindow.mainloop()

    except MC.Error as err:
        print(err)
    finally:
        if(conn.is_connected()):
            cursor.close()
            conn.close()

label_0 = Label(window, width = 64, bg = "#d1a0ad", font = ("Helvetica", 11), text = "Stephi Place Software vous demande de vous connecter avant d'accéder au logiciel :")
label_0.place(x = 10 , y = 20)
label_1 = Label(window, width = 20, height = 2, bg = "#d1a0ad", font = ("Helvetica", 10), text = " Votre identifiant -> ")
label_1.place(x = 105, y = 60)
value = Entry(window, width = 35, bg = "#d1a0ad", font = ("Helvetica", 10))
value.place(x = 305, y = 68)
button = Button(window, width = 20, height = 2,bg = "#D5D5D5", font = ("Helvetica", 8), text = "Valider", command = action)
button.place(x = 230, y = 120)

window.mainloop()   #affichage de la fenêtre
